### ISSUE TITLE
Unify HTML structure for RTL

### ISSUE THREAD

**Issue by alexhass** [yamlcss/yaml#16]
In RTL layouts the search button is aligned to right if the input button comes after the input field in HTML code. As all CMS render every field the same way and don't move the submit button above the input field it would be better to change the CSS than the HTML here.

LTR:

```
<form class="ym-searchform">
  <input class="ym-searchbutton" type="submit" value="Search">
  <input class="ym-searchfield" type="search" placeholder="Search...">
</form>
```

RTL:

```
<form class="ym-searchform">
  <input class="ym-searchbutton" type="submit" value="Search">
  <input class="ym-searchfield" type="search" placeholder="Search...">
</form>
```

HTML code should be structured like the current LTR code also in RTL. Can we change this, please?

What is the technical reason for below CSS code in hlist RTL file? It seems to cause this wrong alignment. Removing it fixes the issue.

```
.ym-hlist * {
  direction: ltr !important;
}
```

**Comment by djesse** [comment]
Changing direction is needed as a IE7 workaround for RTL support. Fixed issue: 41b2104e3f29dae7c7521a681dbfe85bd3182f76

**Comment by alexhass** [comment]
Typo in commit "changee"

**Comment by alexhass** [comment]
Something is wrong in the generated css file, too. Empty hlist... And two hlist... One only with two comments.

**Comment by alexhass** [comment]
For me only this worked. Adding it to .ym-hlist .ym-searchform does not work, but may be related to my HTML code. Have not reviewed the yaml demo files yet.

```
.ym-hlist .ym-searchform * {
  direction: rtl !important;
}
```
