### ISSUE TITLE
Remove ym-fbox margin/padding if form item is inside a table cell

### ISSUE THREAD

**Issue by alexhass** [yamlcss/yaml#18]
Issue:
![2013-06-26_125746](https://f.cloud.github.com/assets/4450722/708725/4c0a7b4e-de4f-11e2-89d9-de1f5f59fe7f.png)

Solution:

```
  .ym-form table .ym-fbox {
    padding-left: 0;
    padding-right: 0;
    margin-top: 0;
    margin-bottom: 0;
  }
```

![2013-06-26_135137](https://f.cloud.github.com/assets/4450722/708888/d0156bcc-de56-11e2-8f66-61b28035aa34.png)

**Comment by djesse** [comment]
Sorry, within a form there can be any markup. YAML can't predefine any possible combination here. This is definitely part of the users work. Won't "fix" this.
