### ISSUE TITLE
Form linearisation should not stretch input type image

### ISSUE THREAD

**Issue by alexhass** [yamlcss/yaml#19]
I have there one example that may be a bit specific, but shown a problem with input type image if the form is very small.

Normal page width:
![2013-06-26_030347](https://f.cloud.github.com/assets/4450722/708750/180c97b8-de50-11e2-87c0-e8af03cfdbd3.png)

Small page width (<480px):
![2013-06-26_030319](https://f.cloud.github.com/assets/4450722/708751/1b334cfc-de50-11e2-91b0-f4fe024e7f35.png)

I'm wondering if we may need to explicitly exclude type image all times to prevent such issues with image buttons.

**Comment by alexhass** [comment]
Why is it not possible to attach example HTML files here???

**Comment by djesse** [comment]
Should be fixed in e576ae2cda07dc5d391524c470b3359e3ae0f5bd

**Comment by alexhass** [comment]
Yes, this works.
