### ISSUE TITLE
Rename .secondary as it could cause collisions

### ISSUE THREAD

**Issue by alexhass** [yamlcss/yaml#27]
I have collisions with .secondary class with some Drupal stuff.

We should use class names with less conflict potential. Also if this is only an example in the layout file. :-)

**Comment by djesse** [comment]
If Drupal stuff collides with a typical class name as ".secondary" shouldn't that Drupal stuff avoid polluting the markup with its own classes or use namespaceing?

**Comment by alexhass** [comment]
That's correct. We have some cases for this https://drupal.org/node/2029187 and https://drupal.org/node/1921610. I can remove the secondary class from the menu with theming, but I thought I should better note that such short names should also prefixed in YAML or have longer names.

**Comment by djesse** [comment]
The class .secondary neither short nor it is part of the framework. It's simply a class, I use in the demo layout as any other user can do in the same way. Therefore there's no reason to change anything here. If Drupal modules generate markup by themself, they have to make sure, not to collide with the user layout.
