### ISSUE TITLE
Columnar: ym-message not shown below checkbox

### ISSUE THREAD

**Issue by alexhass** [yamlcss/yaml#29]
Repro case: http://www.yaml.de/docs/index.html#yaml-forms

```
<div class="ym-fbox ym-fbox-check">
  <input type="checkbox" name="newsletter" id="newsletter">
  <label for="newsletter">Sign me up for your newsletter</label>
  <div class="ym-message">Test test tes test test test test.</div>
</div>
```

![2013-06-28_225730](https://f.cloud.github.com/assets/4450722/724458/5fe3804c-e035-11e2-97e4-1016025e39bb.png)

**Comment by alexhass** [comment]
More examples

![2013-06-28_230122](https://f.cloud.github.com/assets/4450722/724479/eacc5620-e035-11e2-9d05-c892a8047db9.png)

**Comment by djesse** [comment]
Class .ym-message is intended to be placed before the form elements due to accessibility reasons as the error message sould be read (by screenreaders) before the user enters the according form element.

If you want to put additional information behind the form element, this might confuse users because its not clear if this text is related to the previous or next form element. If you still want to do so, you should use .ym-fbox-wrap in this situation. Please check if this fixes your problem.

**Comment by alexhass** [comment]
Interesting... wasn't aware of this screen reader detail. Can you add this to the documentation pages, please? In Drupal this is always below the form field, but I believe I change this via theming. For me it looks pretty strange for normal readers.

This don't work properly:

```
<div class="form-item ym-fbox ym-fbox-check form-type-checkbox form-item-extra-private">
    <div class="description ym-message">Private Felder werden (auch im Formular) nur Benutzern mit Zugriff auf Ergebnisse angezeigt.</div>
    <input type="checkbox" id="edit-extra-private" name="extra[private]" value="1" class="form-checkbox">  
    <label class="option" for="edit-extra-private">Privat </label>
</div>
```

![2013-06-29_182122](https://f.cloud.github.com/assets/4450722/726182/b5156626-e0d9-11e2-84c8-1829b8642ed4.png)

This also works:

```
<div class="form-item ym-fbox ym-fbox-check form-type-checkbox form-item-extra-private">
  <div class="ym-fbox-wrap">
    <div class="description ym-message">Private Felder werden (auch im Formular) nur Benutzern mit Zugriff auf Ergebnisse angezeigt.</div>
    <input type="checkbox" id="edit-extra-private" name="extra[private]" value="1" class="form-checkbox">  
    <label class="option" for="edit-extra-private">Privat </label>
  </div>
</div>
```

![2013-06-29_183739](https://f.cloud.github.com/assets/4450722/726193/41a2a8e2-e0da-11e2-82bc-c55274cdcc2a.png)

If I understand this correct I need to wrap every field into an fbox just to be save for columnar? It's not documented... that's why I'm not sure.

And this also works:

```
<div class="form-item ym-fbox ym-fbox-check form-type-checkbox form-item-extra-year-textfield">
  <div class="ym-fbox-wrap">
    <input type="checkbox" id="edit-extra-year-textfield" name="extra[year_textfield]" value="1" class="form-checkbox">   
   <label class="option" for="edit-extra-year-textfield">Ein Textfeld für das Jahr verwenden </label>
   <div class="description ym-message">Wenn ausgewählt, wird das erzeugte Datumsfeld ein Textfeld für das Jahr benutzen. Andernfalls benutzt es eine Selektionsliste.</div>
  </div>
</div>
```

![2013-06-29_184446](https://f.cloud.github.com/assets/4450722/726200/5974d50c-e0db-11e2-8dfa-02aaaa2cfd66.png)

Just writing this down here as it's not documented.

**Comment by alexhass** [comment]
Ups... above seems only working for checkboxes and maybe radios (untested), but not for normal textfields.
