### ISSUE TITLE
Hex colors with 8 chars?

### ISSUE THREAD

**Issue by alexhass** [yamlcss/yaml#3]
All filter selectors in grey-theme.css have 8 chars. What are the correct color values?

Only one example:

```
filter: progid:DXImageTransform.Microsoft.Gradient(GradientType=0, startColorstr='#FF8888CC', endColorstr='#FF6666AA');
```

**Comment by djesse** [comment]
Thes values are correct. Microsoft filters use 8-char values that combine alphatransparency and color code: http://msdn.microsoft.com/en-us/library/ms532997%28v=vs.85%29.aspx
