### ISSUE TITLE
Search input appearance Apple specific?

### ISSUE THREAD

**Issue by alexhass** [yamlcss/yaml#31]
I'm wondering why input type search does not look the same in all browsers. What is the reason for setting -webkit-appearance "textfield" in base.css and not "none"?

With "none" it would look like this on iOS what means it would look like the submit button and all other input fields.

![image](https://f.cloud.github.com/assets/4450722/727684/322453fe-e1b4-11e2-95c2-722852f57bf8.jpg)

Today it look like

![image](https://f.cloud.github.com/assets/4450722/727699/a89da1ec-e1b5-11e2-9d1b-f6e124ba3d4d.jpg)

**Comment by djesse** [comment]
This addresses an issue with Safari 5 and Chrome. These browsers set "appearance" to "searchfield". So this should remain in base.css.

We can get rid of the round corners by adding -webkit-appearance: none; to the searchfield CSS in hlist.css
