### ISSUE TITLE
.ym-inline input's inside radios become grey and underlay next select

### ISSUE THREAD

**Issue by alexhass** [yamlcss/yaml#33]
Columnar layout:
![2013-07-10_214108](https://f.cloud.github.com/assets/4450722/777437/b0c3fd18-e998-11e2-8e56-18038ab1bca3.png)

Example code:

```
<div id="edit-email-option" class="form-radios ym-fbox-wrap">
  <div class="form-item ym-fbox-check form-type-radio form-item-email-option webform-container-inline">
    <input type="radio" id="edit-email-option-custom" name="email_option" value="custom" checked="checked" class="form-radio">
    <label class="option" for="edit-email-option-custom">Address: <input class="ym-inline webform-set-active form-text" placeholder="email@example.com" type="text" id="edit-email-custom" name="email_custom" value="" size="24" maxlength="500"> </label>
  </div>
  <div class="form-item ym-fbox-check form-type-radio form-item-email-option webform-container-inline">
    <input type="radio" id="edit-email-option-component" name="email_option" value="component" class="form-radio">
    <label class="option" for="edit-email-option-component">Component value: <select class="ym-inline webform-set-active form-select" id="edit-email-component" name="email_component"><option value="2">Mail</option><option value="7">Optionen</option></select> </label>
  </div>
</div>
```

Removing ym-fbox-check fixes the input issue, but moves the radio to wrong position. 

Without ym-fbox-check columnar is very broken. See screenshot:

![2013-07-10_214652](https://f.cloud.github.com/assets/4450722/777478/7ba2ac1e-e999-11e2-9f40-62d5b29886fd.png)

**Comment by djesse** [comment]
The framework can't anticipate any theoretically possible combination of form elements. The form module doesn't expect that you mix different form elements within a single identifier-class (e.g. ym-fbox-check). So, in this case your markup isn't the best practice. Use the multicolumn option via YAMLs grids to place the URL field next to the checkbox. Then you can separate styling and functionality.

If you can't do that, please adjust your form theme. This is a special use case that won't need to be "fixed" in the YAML core I think.

**Comment by alexhass** [comment]
I do not think that this is a special case. It's very generic that form element can be mixed.

YAML need to expect this with ym-inline elements.

**Comment by djesse** [comment]
IE6 wrapper classes (e.g. ym-fbox-check) don't allow mixing different form elements. You should change your markup.
