### ISSUE TITLE
Forgotten unit on gray form theme

### ISSUE THREAD

**Issue by SimonWpt** [yamlcss/yaml#36]
[_gray-theme.scss](https://github.com/yamlcss/yaml/blob/master/sass/yaml-sass/forms/_gray-theme.scss#L30)

Line: 30
Error: Missing unit

_line-height: 1.5;_

Should be:

_line-height: 1.5em;_

**Comment by djesse** [comment]
This is not a bug. Unit-less <number> values are typical to set the line-height. More information on MDN;
https://developer.mozilla.org/en-US/docs/Web/CSS/line-height
