### ISSUE TITLE
Overriding YAML

### ISSUE THREAD

**Issue by paolodina** [yamlcss/yaml#37]
Hi, I've some questions about how to correctly override variables in YAML using sass. I'd like to use YAML this way:

```
// This is the main stylesheet file for the site, main.scss
// my overrides to yaml
$ym-text-color: gold;

// import the pieces of yaml I'm interested in
@import "/path/to/yaml/sass/screen/typography";
```

To make the override to work, I have to change `$ym-text-color` in `_yaml-var-typography.scss` from `#444` to `#444 !default`. I'd prefer to leave YAML files untouched, though. And put the override _after_ the import not changing YAML has no effect.

My questions:
1. Why `!default` hasn't been specified for important YAML variables like `$ym-text-color`, `$ym-headings-color`, etc? I noted that Default Print Settings values have `!default` instead.
2. How do I override values without changing YAML source?

**Comment by djesse** [comment]
Hi,

The standard way to modify the configuration would be to modify or create your own or modify the existing _yaml-var-\* files.

Therefore, YAML has !default defined for most important configuration values only. If you want to be able to override all properties, then you have to add !default keywords for all values.

**Comment by jofran73** [comment]
Hi,
I support paolodina's request to add !default to all parameters. It took me a while to figure out why variable-overriding wasn't working for all settings. I don't like to modify external source files.
Thanks,
  Jörg

**Comment by ogai** [comment]
I also support strongly paolodina. It should be possible to change any configuration variable of yaml without the need to touch its scss sources.

**Comment by MacKP** [comment]
+1

**Comment by djesse** [comment]
All Sass variables in YAML5 will have "!default" attached, so they can easily be overwritten in your prefered way.
