### ISSUE TITLE
push and pull is not working in IE6

### ISSUE THREAD

**Issue by RobinQu** [yamlcss/yaml#39]
See the snapshots
https://www.dropbox.com/s/cg2stk85zij3h2g/ie.png

**Comment by djesse** [comment]
Can't reconstruct the problem from a screenshot.

**Comment by RobinQu** [comment]
Sorry for the missing file.

I uploaded the [screenshot](https://www.dropbox.com/s/kvp0dotihsbr167/screenshot.png) again. You can reproduce the bug by opening http://www.yaml.de/demos/custom-grid.html in IE6.
