### ISSUE TITLE
compass compile error

### ISSUE THREAD

**Issue by afattahi54** [yamlcss/yaml#45]
I get below error while running compass compile

Encoding::UndefinedConversionError on line ["655"] of C: "\xC3" from ASCII-8BIT
to UTF-8

I use ruby 2.0.0-p353 ( last version) and get compass last version 0.12.2

The line which generate the error is in the gem\sass\3.2.12\lib\sass\util.rb

 def check_sass_encoding(str, &block)
      return check_encoding(str, &block), nil if ruby1_8?
      # We allow any printable ASCII characters but double quotes in the charset decl
      bin = str.dup.force_encoding("BINARY")
      encoding = Sass::Util::ENCODINGS_TO_CHECK.find do |enc|
        re = Sass::Util::CHARSET_REGEXPS[enc]
        re && bin =~ re
      end
      charset, bom = $1, $2
      if charset
        charset = charset.force_encoding(encoding).encode("UTF-8")
        if endianness = encoding[/[BL]E$/]
          begin
            Encoding.find(charset + endianness)
            charset << endianness
          rescue ArgumentError # Encoding charset + endianness doesn't exist
          end
        end
        str.force_encoding(charset)
      elsif bom
        str.force_encoding(encoding)
      end

```
  str = check_encoding(str, &block)
  return str.encode("UTF-8"), str.encoding <<HERE IS LINE 655
end
```

**Comment by djesse** [comment]
Hi,

looks like your problem is related to Compass/Sass, not to YAML. Compass 0.12.2 works fine with Sass 3.2.8.

Dirk

**Comment by afattahi54** [comment]
Hi Dirk,

Yes it is an issue of compass, as I find this is the issue of @charset "utf-8" 
http://stackoverflow.com/questions/5967626/ruby-1-9-and-sass-encoding-issues-from-ascii-8bit-to-utf-8
I found that the files in static-build folder have the chraset but it seems that the files yaml-sass should also have it.
I am working to see if I can manage this problem.
PS: Same problem with Sass 3.2.8

**Comment by afattahi54** [comment]
I found that you must set Encoding.default_external = "UTF-8" in the config.rb !

**Comment by djesse** [comment]
Hi,

the @charset "utf-8" rule can be found in all source files that will be compiled to real CSS files.

Dirk

**Comment by afattahi54** [comment]
May be it is a SASS/Compass bug !
