### ISSUE TITLE
@media screen { } entfernen

### ISSUE THREAD

**Issue by MacKP** [yamlcss/yaml#56]
Ich würde gerne mit @media arbeiten von SCSS (http://sass-lang.com/documentation/file.SASS_REFERENCE.html#media). Dabei ist mir aufgefallen, das es nicht geht, solange man innerhalb von der @media screen Anweisung arbeitet, die in jeder YAML-Datei liegt.
Wäre es inzwischen nicht sinnvoller, das auszulagern und beim Einbinden der CSS-Dateien zu definieren (sollte man ja eh besser direkt dort machen)?

Viele Grüße

**Comment by djesse** [comment]
Was spricht dagegen unter-/außerhalb der bestehendenden @media Anweisung zu arbeiten? Verzichten will und kann ich nicht darauf, da nur auf diese Weise ein für Entwickler, die noch in CSS entwickeln, lesbarer und benutzbarer Code herauskommt.

**Comment by MacKP** [comment]
Ja, das ist schon klar, das Code rauskommen soll, mit dem man auch ohne SCSS gut arbeiten kann.
Das blöde ist halt eher, das man aktuell immer erst mal @media (was die ja alle Anweisungen immer komplett umschließt) erst mal rausnehmen muss, wenn man die Definition 'inline' machen möchte und nicht erst irgendwo unten drunter oder so.
Ein Weg wäre ja, das alle Anweisungen in SCSS so geschrieben werden würden:

``` css
.ym-wbox {
        @media screen {
                                          padding: 1.5em;
                                          }
    }
```

Das ist allerdings keine wirklich gute Variante wie ich finde :(
Eine andere Methode wäre ja direkt bei der Einbindung in der @import Datei die Zuweisung zu machen ob screen oder print o.ä. Damit könnten dann eigentlich alle Arbeiten wie ich finde.
Wäre das eventuell eine Variante die dir gefallen würde?

Viele Grüße

**Comment by djesse** [comment]
Hi,

genau bei der vorgeschlagenen Schreibweise entstehen ja die enorm vielen unkontrollierten @media Regeln im CSS-Code. Daher geht das nicht. Ein technisch möglicher Weg wäre es sicher, die Dateien zu erlegen und die eigentlichen Inhalte zu importieren. Allerdings ... die meisten CSS-Dateien in YAML5 hat idR. 4 oder mehr Media Queries (Responsive Design eben), was zu einer elenden Zerpflückung und einem endlosen Sass-Datei-Wirrwarr führen würde. Das sehe ich daher auch nicht als Lösung. 

Ich sehe den Ausweg eigentlich darin, den Sass-Entwicklern das als Hausaufgabe mit auf den Weg zu geben. Auf Sass-Basis CSS zu entwickeln ist mitunter sehr angenehm. Allerdings ist mir lesbarer CSS-Code nach wie vor extrem wichtig. Daher sollten sich in Sass beide Wege kombinieren lassen und nicht gegenseitig ausschließen. Also am besten bei Sass mal eine Issue aufmachen.

BTW: YAML5 beta ist in Kürze fertig.

**Comment by MacKP** [comment]
Deine Argumente kann ich gut verstehen. Eventuell gibt es ja irgendwann eine Möglichkeit ^^
Ich schließe das Ticket dann erst mal.

Ich bin sehr sehr gespannt auf YAML5!
