### ISSUE TITLE
border-top of ".ym-vtitle + ul" overriden by ".ym-vlist ul"

### ISSUE THREAD

**Issue by alexhass** [yamlcss/yaml#8]
Repro case: http://www.yaml.de/docs/index.html#yaml-navigation

![unbenannt](https://f.cloud.github.com/assets/4450722/665438/6f0c7460-d79e-11e2-8736-c5d348f780b4.png)

**Comment by djesse** [comment]
Looks like a problem related to the order of styles in the Sass port. Thanks
