### ISSUE TITLE
buttons width inside ym-fbox-footer is not 100% on mobile

### ISSUE THREAD

**Issue by alexhass** [yamlcss/yaml#9]
If screensize is <480px the buttons inside a ym-fbox-footer are not set to 100%. They float very strange. All other buttons are stretched to 100%. I guess this is not the way how it should work.

Repro case: http://www.yaml.de/docs/index.html#yaml-forms -> Form Example

![foto 2](https://f.cloud.github.com/assets/4450722/665508/58d6a0d8-d7a0-11e2-96df-2ef7c85c88e7.png)

**Comment by djesse** [comment]
This is a bug. Thank you
